# Generated by Django 5.1.5 on 2025-08-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_profile_birthday_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
