# Generated by Django 5.1.5 on 2025-08-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
