# Generated by Django 5.1.5 on 2025-08-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default-profile.png', upload_to='profile_images/'),
        ),
    ]
