# Generated by Django 5.2.6 on 2025-10-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_profile_birthday_profile_gender_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
